server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping-cart-service-route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart,/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
        - id: shopping-store-service-route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store,/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses:
                  - NOT_FOUND
                methods:
                  - GET
        - id: warehouse-service-route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse,/warehouse/**
          filters:
            - PrefixPath=/api/v1
        - id: order-service-route
          uri: lb://order
          predicates:
            - Path=/order,/order/**
          filters:
            - PrefixPath=/api/v1
        - id: payment-service-route
          uri: lb://payment
          predicates:
            - Path=/payment,/payment/**
          filters:
            - PrefixPath=/api/v1
        - id: delivery-service-route
          uri: lb://delivery
          predicates:
            - Path=/delivery,/delivery/**
          filters:
            - PrefixPath=/api/v1
