spring:
  application:
    name: aggregator

aggregator:
  kafka:
    bootstrap-servers:
      - localhost:9092
    poll-timeout: 5s
    consumer:
      group-id: aggregator
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
    producer:
      acks: all
      enable-idempotence: true
    topics:
      sensor-events: telemetry.sensors.v1
      snapshots: telemetry.snapshots.v1
