CREATE TABLE IF NOT EXISTS scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    CONSTRAINT uq_scenarios_hub_id_name UNIQUE (hub_id, name)
);

CREATE TABLE IF NOT EXISTS sensors (
    id VARCHAR PRIMARY KEY,
    hub_id VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL,
    operation VARCHAR NOT NULL,
    "value" INTEGER
);

CREATE TABLE IF NOT EXISTS actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL,
    "value" INTEGER
);

CREATE TABLE IF NOT EXISTS scenario_conditions (
    scenario_id BIGINT NOT NULL,
    sensor_id VARCHAR NOT NULL,
    condition_id BIGINT NOT NULL,
    PRIMARY KEY (scenario_id, sensor_id, condition_id),
    CONSTRAINT fk_scenario_conditions_scenario
        FOREIGN KEY (scenario_id) REFERENCES scenarios(id),
    CONSTRAINT fk_scenario_conditions_sensor
        FOREIGN KEY (sensor_id) REFERENCES sensors(id),
    CONSTRAINT fk_scenario_conditions_condition
        FOREIGN KEY (condition_id) REFERENCES conditions(id)
);

CREATE TABLE IF NOT EXISTS scenario_actions (
    scenario_id BIGINT NOT NULL,
    sensor_id VARCHAR NOT NULL,
    action_id BIGINT NOT NULL,
    PRIMARY KEY (scenario_id, sensor_id, action_id),
    CONSTRAINT fk_scenario_actions_scenario
        FOREIGN KEY (scenario_id) REFERENCES scenarios(id),
    CONSTRAINT fk_scenario_actions_sensor
        FOREIGN KEY (sensor_id) REFERENCES sensors(id),
    CONSTRAINT fk_scenario_actions_action
        FOREIGN KEY (action_id) REFERENCES actions(id)
);
