spring:
  application:
    name: analyzer
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/telemetry_analyzer}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

grpc:
  client:
    hub-router:
      address: "static://localhost:59090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    bootstrap-servers:
      - localhost:9092
    poll-timeout: 5s
    hub-consumer:
      group-id: analyzer-hub-events
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
    snapshot-consumer:
      group-id: analyzer-snapshots
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
    topics:
      hub-events: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1
